style:
  font:
    header: "Outfit"
    main: "Montserrat"
    mono: "Fira Code"
    size: 12pt
  color:
    font: "#404040"
    font-accent: "#fdfdfd"
    accent: "#D93930"
    third: "#008A71"
  pagesize:
    width: 210mm
    height: 297mm
  logo: url(https://img.freepik.com/premium-vector/logo-lorem-ipsum-slogan-design-art-template_642953-154.jpg?w=360)
  main-img: url(https://raw.githubusercontent.com/CourtBouillon/weasyprint-samples/master/report/report-cover.jpg)